% CSE Internship Analytics Engine
% Siemens Energy Target: MATLAB Data Processing & Statistical Analysis
% This script reads the aggregated jobs.json, performs category distribution analysis,
% and calculates the hiring volume to predict market trends.

function analyze_internship_trends()
    disp('[*] Starting MATLAB Analytics Engine...');
    
    % 1. Load the JSON data generated by the Python Aggregator
    dataFile = '../docs/data/jobs.json';
    if ~isfile(dataFile)
        error('Data file not found. Ensure Python scanner has run.');
    end
    
    % Read and decode JSON
    rawText = fileread(dataFile);
    data = jsondecode(rawText);
    jobs = data.jobs;
    
    if isempty(jobs)
        disp('No internships found in dataset.');
        return;
    end
    
    disp(['[*] Successfully loaded ', num2str(length(jobs)), ' internships.']);
    
    % 2. Extract Categories for Statistical Analysis
    categories = cell(length(jobs), 1);
    for i = 1:length(jobs)
        if isfield(jobs(i), 'category')
            categories{i} = jobs(i).category;
        else
            categories{i} = 'Software Engineering'; % Default fallback
        end
    end
    
    % 3. Categorical Distribution (Market Demand)
    catCategorical = categorical(categories);
    [counts, catNames] = histcounts(catCategorical);
    
    disp('--- Market Demand by Tech Category ---');
    for i = 1:length(catNames)
        percentage = (counts(i) / length(jobs)) * 100;
        disp([char(catNames(i)), ': ', num2str(counts(i)), ' postings (', num2str(percentage, '%.1f'), '%)']);
    end
    
    % 4. Generate Visualization (Saved for Dashboard Injection)
    fig = figure('Visible', 'off'); % Run headlessly for CI/CD
    bar(counts);
    set(gca, 'xticklabel', catNames);
    title('Active CSE Internships by Tech Domain');
    xlabel('Engineering Category');
    ylabel('Volume of Postings');
    grid on;
    
    % Save the chart to the frontend docs folder
    outputImage = '../docs/data/market_trends.png';
    saveas(fig, outputImage);
    disp(['[*] Successfully generated statistical chart -> ', outputImage]);
    
    disp('[*] MATLAB Analytics Engine Complete.');
end
